{
    "name": "Trajet Intervention Minimal",
    "version": "1.0",
    "depends": ["base"],
    "author": "Generated by Code GPT",
    "category": "Tools",
    "description": "Minimal module to register trajet intervention tree view.",
    "data": ["views/minimal_views.xml"],
    "installable": True,
    "application": False
}
