from . import invoice_send_wizard
from . import invoice_mass_send_wizard
from . import invoice_export_wizard
from . import lolirine_refund_wizard
from . import invoice_audit_wizard
from . import box_consistency_wizard
from . import indexation_audit_wizard
from . import indexation_send_wizard
from . import contract_close_wizard
from . import box_transfer_wizard
